credentials:
  usernames:
    thiagoscav:
      email: thiagoscavazzani@gmail.com
      logged_in: False
      name: Thiago Scavazzani
      password: sec123
    jessyscav:
      email: jessyscavazzani@gmail.com
      logged_in: False
      name: Jessyca Scavazzani
      password: sec123
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name